# This workflow is for doing a code coverage check, reporting to Codecov (linked to my github acc)
name: Code Coverage 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel pytest pytest-cov
        python -m pip install .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run coverage
      run: |
          pytest --cov-config=.coveragerc --cov=./ci_course --cov-report=xml
          cat coverage.xml --cov-branch

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: coverage.xml
